openapi: 3.1.0
info:
  title: Superface GPT API
  version: 1.0.0
paths:
  /api/hub/session:
    post:
      summary: Get session configuration
      operationId: getSession
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: Tool configuration response
servers:
  - url: https://pod.superface.ai
